### ISSUE TITLE
Distinct operation doesn't use provided comparator

### ISSUE THREAD

**Issue by kiselev-dv** [lemire/externalsortinginjava8#1]
Current realization uses default strings equals method

ExternalSort.java line 233
ExternalSort.java line 482

For example: distinct=true and we compare only first 5 characters, strings `AAAAAa` and `AAAAAb` are equals for comparator provided by user. But still, both lines will appears in result file.

Is it a part of design?

**Comment by lemire** [comment]
The current behaviour makes sense to me, but I agree that it is better to change it. So I changed it.

In the current code, a duplicate line is defined as per the provided comparator.

I am closing this issue, re-open if you disagree.

**Comment by kiselev-dv** [comment]
I've implment the same behaviour in my local fork. 
Thank you.
